@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Sat Sep 12 13:31:31 +0530 2026
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -d PRED_PERCEPTRON -i C:\Users\Prasit\Documents\ACSA_RISCV\vivado_gui\rv_perceptron\rv_perceptron.srcs\sources_1\new -prj TB_vlog.prj"
call xvlog  --incr --relax -L uvm -d PRED_PERCEPTRON -i C:\Users\Prasit\Documents\ACSA_RISCV\vivado_gui\rv_perceptron\rv_perceptron.srcs\sources_1\new -prj TB_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
